# Welcome to the example configuration file!
# Remember that if this is in bin/Content.Server or such, it may be overwritten on build.
# Consider copying it and using the --config-file and --data-dir options.

[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 20
port = 25566
bindto = "::,0.0.0.0"
pvs_new_budget = 60
pvs_budget = 150
# Automatic port forwarding!
# Disabled by default because you may not want to do this.
# upnp = true

[status]
# The status server is the TCP side, used by the launcher to determine engine version, etc.
# To be clear: Disabling it makes the launcher unable to connect!
enabled = true

# This is the address and port the status server binds to.
# The port is by default set based on net.port so it will follow what you set there.
# bind = "*:25566"

# This is the address of the OpenDream server as the launcher uses it.
# This is only needed if you're proxying the status HTTP server -
#  by default the launcher will assume the address and port match that of the status server.
# connectaddress = "udp://localhost:25566"

[game]
hostname = "MyServer"
mapname = "stationstation"
maxplayers = 64
type = 1
welcomemsg = "Welcome to the server!"

[opendream]
# The path to DMCompiler's output
json_path = ""
# If true, exceptions will always print to the console in addition to the world.log file (if set)
always_show_exceptions = false
# The port used to listen for /world/Topic() calls
topic_port = 25567

# These are actually client cvars that, currently, have to be passed as program args.
# Documented here in hopes that we'll have a client_config.toml without using the launcher one day
# [net]
# connection_timeout = 300.0
# handshake_interval = 60.0
# handshake_attempts = 5

[hub]
# Set to true to show this server on the public server list
advertise = false
# URL of your server. Fill this in if you have a domain name,
# want to use HTTPS (with a reverse proxy), or other advanced scenarios.
# Must be in the form of an ss14:// or ss14s:// URI pointing to the status API.
server_url = ""

[auth]
# Authentication (accounts):
# 0 = Optional, 1 = Required, 2 = Disabled
# Presumably do require authentication on any public server.
# mode = 0

# If true, even if authentication is required, localhost is still allowed to login directly regardless.
# allowlocal = true

# You should probably never EVER need to touch this, but if you need a custom auth server,
# (the auth server being the one which manages Space Station 14 accounts), you change it here.
# server = https://central.spacestation14.io/auth/

